import {SignedIn, SignedOut, UserButton} from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton } from "@clerk/nextjs";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { data } = api.posts.getAll.useQuery();
  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-slate-400 border-x md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            <SignedIn>
              {/* Mount the UserButton component */}
              <UserButton />
            </SignedIn>
            <SignedOut>
              {/* Signed out users get sign in button */}
              <SignInButton />
            </SignedOut>
          </div>
          {/* Content */}
          <div>
            {data?.map((post) => (
              <div key={post.id}> {post.content}</div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
