import {SignedIn, SignedOut, UserButton, useUser} from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton } from "@clerk/nextjs";
import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const {user} = useUser();
  
  console.log(user);

  if (!user)
    return null;
  return <div className="flex w-full gap-3">
    <img src={user.profileImageUrl} 
          alt="Profile image" 
          className="w-14 h-14 rounded-full"></img>
    <input placeholder="Type some emojis!" className="grow bg-transparent outline-none"/>
  </div> 
 }

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) 
    return <div>Loading...</div>;
  if (!data) 
    return <div>Something went wrong</div>;

  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-slate-400 border-x md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            <SignedIn>
              {/* Mount the UserButton component */}
              <CreatePostWizard />
              <div className="fixed bottom-0 right-0">
                <UserButton />
              </div>
            </SignedIn>
            <SignedOut>
              {/* Signed out users get sign in button */}
              <SignInButton />
            </SignedOut>
          </div>
          {/* Content */}
          <div className="flex flex-col">
            {[...data, ...data]?.map(({post, author}) => (
              <div key={post.id} className="border-b border-slate-400 p-8"> 
                {post.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
